edit monitor log template
ctc-uci/oc-habitats-frontend pull request #100
Opened 2022-04-18 10:23 UTC by ctc-devops

[Figma](https://www.figma.com/file/lf9VVjL1h6YAhqdQXEEr96/%5BDesigner%5D-Wireframes?node-id=2836%3A83522)

- [ ] Frontend
- [ ] Backend
- [ ] Whatever new questions are added here are rendered in "Create Monitor Log" for the volunteers to fill out

* you can start with frontend, see if all the backend functionality is there and correct, then connect them
closes #67

2022-05-27 18:47 UTC, janehvo requested changes
ty for the work it looks really good :D please resolve merge conflicts and address comments asap.

when you resolve conflicts, pls make sure that mobile views and other crucial things on dev are being preserved. gl lol

2022-05-27 18:47 UTC, janehvo commented on src/components/MonitorLog/NonStaticQuestion.jsx
> +            <Text color="#718096">Non-Static</Text>
When displaying to volunteers, there should not be text indicating whether or not a field is non-static.

2022-05-27 18:47 UTC, janehvo commented on src/components/MonitorLog/ListedSpeciesTab.jsx
> +  }, [data, questionAdded, tabEdited]);
Please resolve this to-do and connect listed species to backend end thank you

2022-05-27 18:47 UTC, janehvo commented on src/components/MonitorLog/ListedSpeciesTab.jsx
> +  }, [data, questionAdded, tabEdited]);
Please resolve this to-do and connect listed species to backend end thank you

2022-05-27 18:47 UTC, janehvo commented on src/components/MonitorLog/ListedSpeciesTab.jsx
>                </Button>
This button should also be disabled if they're editing the template.

2022-05-27 18:47 UTC, janehvo commented on src/components/MonitorLog/ListedSpeciesTab.jsx
>                </Button>
This button should also be disabled if they're editing the template.

2022-05-27 18:47 UTC, janehvo commented on src/pages/MonitorLogEditPage.jsx
> +              </Select>
When "Select option" is clicked, the page breaks xD... , maybe have it default to General information if they click "Select option"

2022-05-27 18:47 UTC, janehvo commented on src/pages/MonitorLogEditPage.jsx
> +              </Select>
When "Select option" is clicked, the page breaks xD... , maybe have it default to General information if they click "Select option"

2022-05-27 18:47 UTC, janehvo commented on src/pages/MonitorLogPage.jsx
> +  // })
Delete this if it's not necessary

2022-05-27 18:47 UTC, janehvo commented on src/pages/MonitorLogPage.jsx
> +  // })
Delete this if it's not necessary

2022-05-28 21:37 UTC, ctc-devops commented on src/App.jsx
> +import MonitorLogEditPage from './pages/MonitorLogEditPage';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'MonitorLogEditPage' is defined but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/App.jsx
> +import NewQuestionModal from './components/NewQuestionModal';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'NewQuestionModal' is defined but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/Authentication/Login.jsx
> +    register,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'register' is assigned a value but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/Authentication/Login.jsx
> +  const handleFormSubmission = async data => {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'handleFormSubmission' is assigned a value but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/Authentication/Login.jsx
> +  const handleFormSubmission = async data => {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'data' is defined but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/ListedSpecies/BehaviorsSection.jsx
> +import { Select } from 'chakra-react-select';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Select' is defined but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/ListedSpecies/BehaviorsSection.jsx
> +  const { control } = useFormContext();
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'control' is assigned a value but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/ListedSpecies/BehaviorsSection.jsx
> +  const { control } = useFormContext();
🚫 **[eslint]** <[no-undef](https://eslint.org/docs/rules/no-undef)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'useFormContext' is not defined.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/ListedSpecies/BehaviorsSection.jsx
> +  nesting: PropTypes.arrayOf(PropTypes.string).isRequired,
🚫 **[eslint]** <[react/no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/no-unused-prop-types.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'nesting' PropType is defined but prop is never used

2022-05-28 21:37 UTC, ctc-devops commented on src/components/ListedSpecies/BehaviorsSection.jsx
> +  setNesting: PropTypes.func.isRequired,
🚫 **[eslint]** <[react/no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/no-unused-prop-types.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'setNesting' PropType is defined but prop is never used

2022-05-28 21:37 UTC, ctc-devops commented on src/components/LogTemplateSwitcher.jsx
> +import HumanActivity from './MonitorLog/HumanActivityTab';
🚫 **[eslint]** <[import/no-named-as-default](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-named-as-default.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parse errors in imported module './MonitorLog/HumanActivityTab': Expected corresponding JSX closing tag for <VStack> (196:9)

2022-05-28 21:37 UTC, ctc-devops commented on src/components/LogTemplateSwitcher.jsx
> +import HumanActivity from './MonitorLog/HumanActivityTab';
🚫 **[eslint]** <[import/no-named-as-default-member](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-named-as-default-member.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parse errors in imported module './MonitorLog/HumanActivityTab': Expected corresponding JSX closing tag for <VStack> (196:9)

2022-05-28 21:37 UTC, ctc-devops commented on src/components/MonitorLog/AdditionalSpeciesTab.jsx
> +const AdditionalSpeciesTab = ({ showHeader, isDisabled, isTemplate, species }) => {
🚫 **[eslint]** <[react/prop-types](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/prop-types.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'species' is missing in props validation

2022-05-28 21:37 UTC, ctc-devops commented on src/components/MonitorLog/AdditionalSpeciesTab.jsx
> +                  {species.length === 0 && (
🚫 **[eslint]** <[react/prop-types](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/prop-types.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'species.length' is missing in props validation

2022-05-28 21:37 UTC, ctc-devops commented on src/components/MonitorLog/ListedSpeciesTab.jsx
> +const ListedSpeciesTab = ({ tab, speciesName, speciesCode,speciesId, showHeader, isDisabled, isTemplate }) => {
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Replace `·tab,·speciesName,·speciesCode,speciesId,·showHeader,·isDisabled,·isTemplate·` with `⏎··tab,⏎··speciesName,⏎··speciesCode,⏎··speciesId,⏎··showHeader,⏎··isDisabled,⏎··isTemplate,⏎`
```suggestion
const ListedSpeciesTab = ({
  tab,
  speciesName,
  speciesCode,
  speciesId,
  showHeader,
  isDisabled,
  isTemplate,
}) => {
```

2022-05-28 21:37 UTC, ctc-devops commented on src/components/MonitorLog/ListedSpeciesTab.jsx
> +const ListedSpeciesTab = ({ tab, speciesName, speciesCode,speciesId, showHeader, isDisabled, isTemplate }) => {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'speciesId' is defined but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/MonitorLog/ListedSpeciesTab.jsx
> +const ListedSpeciesTab = ({ tab, speciesName, speciesCode,speciesId, showHeader, isDisabled, isTemplate }) => {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'showHeader' is defined but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/MonitorLog/PredatorsTab.jsx
> +const PredatorsTab = ({ showHeader, isDisabled, isTemplate, predators }) => {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'showHeader' is defined but never used.

2022-05-28 21:37 UTC, ctc-devops commented on src/components/Navbar/NavbarLink.jsx
> +const NavbarLink = ({ text, path = isAdmin, '/', changesMade }) => {
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parsing error: Unexpected token ,

2022-05-29 10:12 UTC, ctc-devops commented on src/components/MonitorLog/AdditionalSpeciesTab.jsx
> +  Grid,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Grid' is defined but never used.

2022-05-29 10:12 UTC, ctc-devops commented on src/components/MonitorLog/AdditionalSpeciesTab.jsx
> +  GridItem,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'GridItem' is defined but never used.

2022-05-29 10:12 UTC, ctc-devops commented on src/components/MonitorLog/AdditionalSpeciesTab.jsx
> +  console.log(getValues());
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-29 10:12 UTC, ctc-devops commented on src/components/MonitorLog/ListedSpeciesTab.jsx
> +  Grid,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Grid' is defined but never used.

2022-05-29 10:12 UTC, ctc-devops commented on src/components/MonitorLog/ListedSpeciesTab.jsx
> +  GridItem,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'GridItem' is defined but never used.

2022-05-29 10:12 UTC, ctc-devops commented on src/components/MonitorLog/ListedSpeciesTab.jsx
> +  speciesId,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'speciesId' is defined but never used.

2022-05-29 10:12 UTC, ctc-devops commented on src/components/MonitorLog/ListedSpeciesTab.jsx
> +  showHeader,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'showHeader' is defined but never used.

2022-05-29 10:12 UTC, ctc-devops commented on src/components/MonitorLog/NonStaticQuestion.jsx
> +  isDisabled: PropTypes.bool,
🚫 **[eslint]** <[react/require-default-props](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/require-default-props.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>propType "isDisabled" is not required, but has no corresponding defaultProps declaration.

2022-05-30 00:13 UTC, janehvo approved these changes

2022-05-30 00:13 UTC, merged