more-volunteer-dashboard
ctc-uci/oc-habitats-frontend pull request #112
Opened 2022-05-01 19:44 UTC by ctc-devops

- [ ] Match design updates
- [ ] Finish backend connection
- [ ] Mobile design
closes #111

2022-05-02 21:38 UTC, ctc-devops commented on src/components/VolunteerDashboard/UnsubmittedLogDraft.jsx
> +import { Flex, Box, Button, Text } from '@chakra-ui/react';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Box' is defined but never used.

2022-05-03 04:59 UTC, ctian1 requested changes

2022-05-03 04:59 UTC, ctian1 commented on src/components/VolunteerDashboard/RecentlySubmittedLog.jsx
> +const setDetails = status => {
this should just be an object to map status to details

2022-05-03 05:18 UTC, ctian1 approved these changes

2022-05-03 05:18 UTC, merged