connect-admin-dashboard
ctc-uci/oc-habitats-frontend pull request #134
Opened 2022-05-26 06:29 UTC by ctc-devops

Connect admin dashboard page to the backend.
Backend route is `/dashboard`
closes #125

2022-06-01 08:18 UTC, ctc-devops commented on src/pages/AdminDashboardPage.jsx
> +import { React, useState, useEffect, useCallback } from 'react';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'useCallback' is defined but never used.

2022-06-01 08:18 UTC, ctc-devops commented on src/pages/AdminDashboardPage.jsx
> +        console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-06-01 08:18 UTC, ctc-devops commented on src/pages/AdminDashboardPage.jsx
> +
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Delete `····`
```suggestion

```

2022-06-02 04:03 UTC, janehvo requested changes

2022-06-02 04:03 UTC, janehvo commented on src/pages/HomePage.jsx
> +import { useUserContext } from '../common/UserContext/UserContext';
This is defined twice please remove one.

2022-06-02 04:08 UTC, janehvo approved these changes
sgtmlgtm

2022-06-02 04:08 UTC, merged