update monitor log
ctc-uci/oc-habitats-frontend pull request #28
Opened 2022-01-30 23:25 UTC by ctc-devops

[There have been design changes that need to be implemented on the monitor log page.](https://www.figma.com/file/lf9VVjL1h6YAhqdQXEEr96/%5BDesigner%5D-Wireframes?node-id=366%3A27664)

Note: Listed species tabs (snowy plover/least tern) and additional species tab is subject to change so you can avoid changing for now

- [ ] Separate monitor log components into tabs
- [ ] Review & Submit tab
- [ ] Monitoring session partners
closes #23

2022-02-15 22:28 UTC, janehvo commented on src/pages/MonitorLogPage.jsx
> +          <Tab>Snowy Polvers</Tab>
change to "Snow Plover"

2022-02-15 23:14 UTC, janehvo requested changes

2022-02-15 23:14 UTC, janehvo commented on src/components/monitorLog/SectionName.jsx
> +function SectionName({ options }) {
Change component/file name to "GeneralInfo"

2022-02-15 23:14 UTC, janehvo commented on src/pages/MonitorLogPage.jsx
> +          </TabPanel>
Need to be separated with some more fields added based on the design

2022-02-16 05:33 UTC, janehvo commented on src/pages/MonitorLogPage.jsx
> +          </TabPanel>
If you can't get this done by tomorrow, it can be pushed to future sprint

2022-02-17 20:54 UTC, janehvo requested changes

2022-02-17 20:54 UTC, janehvo commented on src/components/monitorLog/HumanActivity.jsx
> +function HumanActivity() {
All human activity fields need to be stored somewhere. Implement this logic with useState hooks

2022-02-17 20:54 UTC, janehvo commented on src/components/monitorLog/Predators.jsx
> +function Predators() {
All predator fields need to be stored somewhere. Implement this logic with useState hooks

2022-02-17 23:35 UTC, janehvo commented
Also can you add this to App.css? This makes sure the page doesn't shift when there's a scrollbar

```
html {
  overflow-y: scroll
}
```

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalSitting(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalWalkingRunning(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalBikes(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalSurfers(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalSports(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalFires(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalFishing(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalVehicles(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalEquipmentATV(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalDogsOnLeash(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +                  props.setTotalDogsOffLeash(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +              props.setTOutreachNotes(e.target.value);
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/HumanActivity.jsx
> +              props.setOtherNotes(e.target.value);
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/Predators.jsx
> +                  props.setTotalCrows(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/Predators.jsx
> +                  props.setTotalRavens(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/Predators.jsx
> +                  props.setTotalRaptors(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/Predators.jsx
> +                  props.setTotalHorses(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/Predators.jsx
> +                  props.setTotalCoyotes(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/Predators.jsx
> +                  props.setTotalFoxes(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/Predators.jsx
> +                  props.setTotalCats(parseInt(e, 10));
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-18 07:48 UTC, ctc-devops commented on src/components/monitorLog/Predators.jsx
> +              props.setOtherPredators(e.target.value);
🚫 **[eslint]** <[react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/destructuring-assignment.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Must use destructuring props assignment

2022-02-21 22:19 UTC, ctian1 approved these changes

2022-02-21 22:19 UTC, merged