update section segments page
ctc-uci/oc-habitats-frontend pull request #57
Opened 2022-03-09 20:46 UTC by ctc-devops

[This is the page for admins to edit sections/segments](https://www.figma.com/file/lf9VVjL1h6YAhqdQXEEr96/%5BDesigner%5D-Wireframes?node-id=2008%3A65240)

The SNPL/CLTE columns can be left out for now

- [ ] Update frontend
- [ ] Integrate with backend (stretch goal)
closes #47

2022-03-11 00:50 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +function CreateNewSectionSegment(onAddSegment, addSection) {
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'onAddSegment' is defined but never used.

2022-03-11 00:50 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +function CreateNewSectionSegment(onAddSegment, addSection) {
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'addSection' is defined but never used.

2022-03-11 00:50 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +  const { isOpen, onOpen, onClose } = useDisclosure();
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'isOpen' is assigned a value but never used.

2022-03-11 00:50 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +  const { isOpen, onOpen, onClose } = useDisclosure();
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'onClose' is assigned a value but never used.

2022-03-11 02:09 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +function CreateNewSectionSegment(onAddSegment, addSection) {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'onAddSegment' is defined but never used.

2022-03-11 02:09 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +function CreateNewSectionSegment(onAddSegment, addSection) {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'addSection' is defined but never used.

2022-03-11 02:09 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +  const { isOpen, onOpen, onClose } = useDisclosure();
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'isOpen' is assigned a value but never used.

2022-03-11 02:09 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +  const { isOpen, onOpen, onClose } = useDisclosure();
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'onClose' is assigned a value but never used.

2022-04-02 22:01 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +import Section from './Section';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Section' is defined but never used.

2022-04-02 22:01 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  const volHandleChange = event => setVolInput(event.target.value);
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'volHandleChange' is assigned a value but never used.

2022-04-02 22:01 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  const adminNameHandleChange = event => setAdminName(event.target.value);
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'adminNameHandleChange' is assigned a value but never used.

2022-04-02 22:01 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  const adminEmailHandleChange = event => setAdminEmail(event.target.value);
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'adminEmailHandleChange' is assigned a value but never used.

2022-04-02 22:01 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +import { AddIcon } from '@chakra-ui/icons';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'AddIcon' is defined but never used.

2022-04-02 22:01 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +  const { isOpen, onOpen, onClose } = useDisclosure();
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'onOpen' is assigned a value but never used.

2022-04-04 18:36 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  const [volInput, setVolInput] = useState('');
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'volInput' is assigned a value but never used.

2022-04-04 18:36 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  const [volInput, setVolInput] = useState('');
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'setVolInput' is assigned a value but never used.

2022-04-04 18:36 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  const [adminName, setAdminName] = useState('');
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'adminName' is assigned a value but never used.

2022-04-04 18:36 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  const [adminName, setAdminName] = useState('');
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'setAdminName' is assigned a value but never used.

2022-04-04 18:36 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  const [adminEmail, setAdminEmail] = useState('');
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'adminEmail' is assigned a value but never used.

2022-04-04 18:36 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  const [adminEmail, setAdminEmail] = useState('');
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'setAdminEmail' is assigned a value but never used.

2022-04-04 18:36 UTC, ctc-devops commented on src/pages/SectionPage.jsx
> +function CreateNewSectionSegment(onAddSegment, addSection) {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'CreateNewSectionSegment' is defined but never used.

2022-04-07 02:27 UTC, ctc-devops commented on src/components/Segment.jsx
> +  distance,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'distance' is defined but never used.

2022-04-10 21:36 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  let newSecId = '';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'newSecId' is assigned a value but never used.

2022-04-10 21:36 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +  let newSecMapLink = '';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'newSecMapLink' is assigned a value but never used.

2022-04-19 18:28 UTC, astraljdc commented
pretty sure that's something with my yarn, can we just discard the yarn.lock that I think was pushed by me?
I don't think that it was even added in my stage commit

2022-04-30 20:14 UTC, janehvo requested changes

2022-04-30 20:14 UTC, janehvo commented on src/components/SectionTable/SectionTableRow.jsx
> +  // fixme this is editing a segment?
Remove comment

2022-04-30 20:14 UTC, janehvo commented on src/components/SectionTable/SectionTableRow.jsx
> +              // }}
Delete

2022-04-30 20:14 UTC, janehvo commented on src/components/SectionTable/SectionTableRow.jsx
> +  // );
Delete

2022-04-30 20:14 UTC, janehvo commented on src/components/NewSectionSegmentPopup.jsx
> +      });
You can probably delete this since it was used for testing

2022-05-08 17:15 UTC, ctc-devops commented on src/components/NewSectionSegmentPopup.jsx
> +      console.log({
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-08 17:15 UTC, ctc-devops commented on src/components/SectionTable/SectionTableRow.jsx
> +  console.log('DATA', sectionID);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-08 17:15 UTC, ctc-devops commented on src/components/SectionTable/SectionTableRow.jsx
> +      console.log(putData);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-08 18:47 UTC, ctc-devops commented on src/components/SectionTable/SectionTableRow.jsx
> +      alert(err);
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-05-08 18:47 UTC, ctc-devops commented on src/components/SectionTable/SectionTableRow.jsx
> +      console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-08 18:47 UTC, ctc-devops commented on src/components/SectionTable/SectionTableRow.jsx
> +      alert(err);
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-05-08 21:48 UTC, janehvo approved these changes

2022-05-08 21:48 UTC, merged