monitor-log-submissions-page
ctc-uci/oc-habitats-frontend pull request #82
Opened 2022-03-31 07:27 UTC by ctc-devops

[Figma](https://www.figma.com/file/lf9VVjL1h6YAhqdQXEEr96/%5BDesigner%5D-Wireframes?node-id=2770%3A83754)

- [ ] Format approval status badge and training status badge in table
- [ ] Fix table padding, round corners
- [ ] Select month should be a datepicker
- [ ] Add top buttons
- [ ] Backend integration
closes #60

2022-04-05 19:32 UTC, ctc-devops commented on src/pages/AdminPage.jsx
> +  const getSpecies = async () => {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'getSpecies' is assigned a value but never used.

2022-04-05 19:32 UTC, ctc-devops commented on src/pages/AdminPage.jsx
> +      console.log(res.data);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-06 02:33 UTC, ctc-devops commented on src/pages/AdminPage.jsx
> +  const [change, setChange] = useState(true);
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'setChange' is assigned a value but never used.

2022-04-06 02:33 UTC, ctc-devops commented on src/pages/AdminPage.jsx
> +                  console.log(reminderValue);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-11 04:02 UTC, ctc-devops commented on src/components/AdminPageTable/AdminPageHeader.jsx
> +import { Thead, Tr, Th, Checkbox, Button } from '@chakra-ui/react';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Checkbox' is defined but never used.

2022-04-11 04:02 UTC, ctc-devops commented on src/components/AdminPageTable/AdminPageHeader.jsx
> +import { Thead, Tr, Th, Checkbox, Button } from '@chakra-ui/react';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Button' is defined but never used.

2022-04-11 04:02 UTC, ctc-devops commented on src/components/AdminPageTable/AdminPageTable.jsx
> +import { Table, Tr, Td, Checkbox, HStack, Text, Tbody } from '@chakra-ui/react';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'HStack' is defined but never used.

2022-04-11 04:02 UTC, ctc-devops commented on src/components/AdminPageTable/AdminPageTable.jsx
> +import { Table, Tr, Td, Checkbox, HStack, Text, Tbody } from '@chakra-ui/react';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Text' is defined but never used.

2022-04-11 04:02 UTC, ctc-devops commented on src/pages/AdminPage.jsx
> +      const submissions = res.data.map(submission => ({}));
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'submission' is defined but never used.

2022-04-11 04:02 UTC, ctc-devops commented on src/pages/AdminPage2.jsx
> +import { Container, Heading, Flex, Text } from '@chakra-ui/react';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Flex' is defined but never used.

2022-04-11 05:04 UTC, ctc-devops commented on src/pages/AdminPage2.jsx
> +import ExportLogsModal from '../components/AdminPageTable/ExportLogsModal';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'ExportLogsModal' is defined but never used.

2022-04-11 06:49 UTC, ctc-devops commented on src/components/AdminPageTable/SetReminderModal.jsx
> +  useToast,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'useToast' is defined but never used.

2022-04-11 06:49 UTC, ctc-devops commented on src/components/AdminPageTable/SetReminderModal.jsx
> +  VStack,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'VStack' is defined but never used.

2022-04-21 04:14 UTC, ctian1 requested changes
Looks good, just clean up the import warnings, etc. and we can merge

2022-04-21 04:14 UTC, ctian1 commented on src/components/AdminPageTable/temp.txt
> +    <>
delete this

2022-04-21 04:14 UTC, ctian1 commented on src/App.jsx
> +import AdminPage from './pages/AdminPage2'; // monitor-log table
why AdminPage2

2022-04-28 03:21 UTC, ctc-devops commented on src/components/AdminPageTable/AdminPageFilters.jsx
> +  segments: PropTypes.arrayOf(PropTypes.object).isRequired,
🚫 **[eslint]** <[react/forbid-prop-types](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/forbid-prop-types.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Prop type "object" is forbidden

2022-04-28 03:34 UTC, ctian1 commented on src/theme/theme.js
> -    ochBluePress: '#156071',
add this back

2022-04-28 03:36 UTC, ctian1 commented on yarn.lock
> +<<<<<<< HEAD
this shouldn't be here. [try this](https://stackoverflow.com/a/42939114/3624290) to fix it

2022-04-28 04:13 UTC, janehvo approved these changes
lgtm, ty for addressing comments

2022-04-28 04:19 UTC, ctian1 approved these changes

2022-04-28 04:19 UTC, merged