dashboard page
ctc-uci/oc-habitats-frontend pull request #85
Opened 2022-04-02 00:54 UTC by ctc-devops

[Figma](https://www.figma.com/file/lf9VVjL1h6YAhqdQXEEr96/%5BDesigner%5D-Wireframes?node-id=2023%3A64119)

- [ ] Toasts
- [ ] Remember hidden toasts with local storage
- [ ] Segment assignments
- [ ] Unsubmitted log drafts
- [ ] Recently submitted logs
- [ ] Connect to backend ... some features may not exist yet ([backend#31](https://github.com/ctc-uci/oc-habitats-backend/issues/31))
closes #65

2022-04-26 20:48 UTC, ctc-devops commented on src/components/Navbar/NavbarMobile.jsx
> +  const user = {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'user' is assigned a value but never used.

2022-04-26 20:48 UTC, ctc-devops commented on src/components/Navbar/NavbarMobile.jsx
> +  const adminAccountDrop = [
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'adminAccountDrop' is assigned a value but never used.

2022-04-26 20:48 UTC, ctc-devops commented on src/components/Navbar/NavbarMobile.jsx
> +  const volunteerAccountDrop = [
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'volunteerAccountDrop' is assigned a value but never used.

2022-04-26 20:48 UTC, ctc-devops commented on src/pages/HomePage.jsx
> +      console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-26 20:48 UTC, ctc-devops commented on src/pages/HomePage.jsx
> +  console.log(userData);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-26 20:48 UTC, ctc-devops commented on src/pages/HomePage.jsx
> +  console.log(userData?.segments);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-28 03:31 UTC, janehvo commented on Procfile
> +web: node --optimize_for_size --max_old_space_size=920 --gc_interval=100 node_modules/.bin/serve -s build
I think you can delete this file?

2022-04-28 03:55 UTC, janehvo commented on src/pages/HomePage.jsx
> +          Welcome Back, Peter!
Replace `Peter` with the user's first name, should be `userData.firstName`

2022-04-28 03:55 UTC, janehvo commented on src/pages/HomePage.jsx
> +          />
Remove these hard coded things since you already finished mapping assignments from `userData`

2022-04-28 22:59 UTC, janehvo requested changes

2022-04-28 22:59 UTC, janehvo commented on src/pages/HomePage.jsx
> +export default HomePage;
Can you change the file name and the page to `VolunterDashboard`

2022-04-28 23:17 UTC, janehvo approved these changes

2022-04-28 23:17 UTC, merged