switch volunteer admin view
ctc-uci/oc-habitats-frontend pull request #88
Opened 2022-04-04 21:23 UTC by ctc-devops

closes #80

2022-05-01 02:09 UTC, janehvo commented
@rochellenixon hi Rochelle! now that the dashboards have been merged, you can work on rendering the respective view

2022-05-01 02:10 UTC, janehvo reviewed
hi Rochelle! now that the dashboards have been merged, you can work on rendering the respective view

2022-05-04 22:38 UTC, ctc-devops commented on src/App.jsx
> +  console.log(isAdmin);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-04 22:38 UTC, ctc-devops commented on src/App.jsx
> +  console.log(onAdminPortal);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  Button,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Button' is defined but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  Avatar,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Avatar' is defined but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  Menu,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Menu' is defined but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  MenuButton,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'MenuButton' is defined but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  MenuItem,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'MenuItem' is defined but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  MenuList,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'MenuList' is defined but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  Text,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Text' is defined but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +import { FaSignOutAlt } from 'react-icons/fa';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'FaSignOutAlt' is defined but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  console.log(typeof setOnAdminPortal);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  const user = {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'user' is assigned a value but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/Navbar.jsx
> +  const togglePortal = () => {
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'togglePortal' is assigned a value but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/ProfileDropdown.jsx
> +  Button,
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'Button' is defined but never used.

2022-05-04 22:38 UTC, ctc-devops commented on src/components/Navbar/ProfileDropdown.jsx
> +import { FaSignOutAlt } from 'react-icons/fa';
⚠️ **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'FaSignOutAlt' is defined but never used.

2022-05-08 21:56 UTC, janehvo requested changes
Hi on top of what was requested, can you also delete unnecessary comments? Like the commented out arrays/objects. ty

2022-05-08 21:56 UTC, janehvo commented on src/components/Navbar/Navbar.jsx
>      { text: 'Emergency Numbers', path: '/emergency-numbers' },
Can you fix this so that the path is just `/numbers`? And change it anywhere else where it's incorrect. Thank you :)

2022-05-08 21:56 UTC, janehvo commented on src/App.jsx
>  // TO-DO: Navbar based on screen width
Delete this comment; it's already been done

2022-05-09 19:38 UTC, janehvo approved these changes
lgtm ;)

2022-05-15 18:42 UTC, merged